plugins {
    id 'com.android.application'
}
android {
    namespace 'com.merayetak.quiz'
    compileSdk 35
    defaultConfig {
        applicationId 'com.merayetak.quiz'
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName '2.0'
    }
    signingConfigs {
        stable {
            storeFile file('merayetak.keystore')
            storePassword 'merayetak'
            keyAlias 'merayetak'
            keyPassword 'merayetak'
        }
    }
    buildTypes {
        debug { signingConfig signingConfigs.stable }
        release { minifyEnabled false; signingConfig signingConfigs.stable }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
